### PR TITLE
Add essential info about the nature of git repositories

### PR DESCRIPTION
**Pull request by eldond**
edit tests might prefer the top comment to be blank, so I'll write a thing here
-=******************************eldond******************************=-
new new new stuff put in your comment! NEW NEW NEW, STUFF PUT IN! INTO YOUR COMMENT!
-=******************************eldond******************************=-
new new new stuff put in your comment! NEW NEW NEW, STUFF PUT IN! INTO YOUR COMMENT!

### CODE REVIEW

**Comment by eldond** [comment]
This was intended to support a regression test for OMFIT git tools for handling inter-fork pull requests, but it won't work since neither side of the fork is OMFIT-source. Whoops.

**Comment by eldond** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_eldond

**Comment by orso82** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_meneghini

**Comment by smithsp** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_sterlingsmith

**Comment by smithsp** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_sterlingsmith

**Comment by krystophny** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_ert

**Comment by krystophny** [comment]
this is a temporary automatic comment for use by TestOmfitGithub.test_edit_github_other_comment()
keyword_to_search_for_10539_ert

**Pull request closed without merging**
